// flow-typed signature: 71c70f610c59975ba7ed25f5ed4a2c27
// flow-typed version: <<STUB>>/koa-body_v^2.5.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-body'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-body' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa-body/index' {
  declare module.exports: $Exports<'koa-body'>;
}
declare module 'koa-body/index.js' {
  declare module.exports: $Exports<'koa-body'>;
}
