// flow-typed signature: d731cb9b18720f4cf204447fa5d4d547
// flow-typed version: <<STUB>>/@polymathnetwork/auth_v0.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@polymathnetwork/auth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@polymathnetwork/auth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@polymathnetwork/auth/babel.config' {
  declare module.exports: any;
}

declare module '@polymathnetwork/auth/src/actions' {
  declare module.exports: any;
}

declare module '@polymathnetwork/auth/src/helpers' {
  declare module.exports: any;
}

declare module '@polymathnetwork/auth/src/index' {
  declare module.exports: any;
}

declare module '@polymathnetwork/auth/src/networks' {
  declare module.exports: any;
}

declare module '@polymathnetwork/auth/src/PolymathAuth' {
  declare module.exports: any;
}

declare module '@polymathnetwork/auth/src/reducer' {
  declare module.exports: any;
}

declare module '@polymathnetwork/auth/webpack.dev' {
  declare module.exports: any;
}

declare module '@polymathnetwork/auth/webpack.prod' {
  declare module.exports: any;
}

// Filename aliases
declare module '@polymathnetwork/auth/babel.config.js' {
  declare module.exports: $Exports<'@polymathnetwork/auth/babel.config'>;
}
declare module '@polymathnetwork/auth/src/actions.js' {
  declare module.exports: $Exports<'@polymathnetwork/auth/src/actions'>;
}
declare module '@polymathnetwork/auth/src/helpers.js' {
  declare module.exports: $Exports<'@polymathnetwork/auth/src/helpers'>;
}
declare module '@polymathnetwork/auth/src/index.js' {
  declare module.exports: $Exports<'@polymathnetwork/auth/src/index'>;
}
declare module '@polymathnetwork/auth/src/networks.js' {
  declare module.exports: $Exports<'@polymathnetwork/auth/src/networks'>;
}
declare module '@polymathnetwork/auth/src/PolymathAuth.js' {
  declare module.exports: $Exports<'@polymathnetwork/auth/src/PolymathAuth'>;
}
declare module '@polymathnetwork/auth/src/reducer.js' {
  declare module.exports: $Exports<'@polymathnetwork/auth/src/reducer'>;
}
declare module '@polymathnetwork/auth/webpack.dev.js' {
  declare module.exports: $Exports<'@polymathnetwork/auth/webpack.dev'>;
}
declare module '@polymathnetwork/auth/webpack.prod.js' {
  declare module.exports: $Exports<'@polymathnetwork/auth/webpack.prod'>;
}
