// flow-typed signature: abf3c857eaee3b9b5a46952bf3b3dc78
// flow-typed version: <<STUB>>/@polymathnetwork/shared_v0.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@polymathnetwork/shared'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@polymathnetwork/shared' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@polymathnetwork/shared/migrations/1_deploy_token' {
  declare module.exports: any;
}

declare module '@polymathnetwork/shared/migrations/2_deploy_contracts' {
  declare module.exports: any;
}

declare module '@polymathnetwork/shared/truffle' {
  declare module.exports: any;
}

// Filename aliases
declare module '@polymathnetwork/shared/migrations/1_deploy_token.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/shared/migrations/1_deploy_token'
  >;
}
declare module '@polymathnetwork/shared/migrations/2_deploy_contracts.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/shared/migrations/2_deploy_contracts'
  >;
}
declare module '@polymathnetwork/shared/truffle.js' {
  declare module.exports: $Exports<'@polymathnetwork/shared/truffle'>;
}
