// flow-typed signature: 2e1a45518f05b2f51f1433a2b79ecfbc
// flow-typed version: <<STUB>>/@polymathnetwork/ui_v0.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@polymathnetwork/ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@polymathnetwork/ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@polymathnetwork/ui/babel.config' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/jest.config' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/Countdown' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/DummyPage' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/Footer' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/inputs/CheckboxInput' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/inputs/DatePickerInput' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/inputs/DatePickerRangeInput' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/inputs/RadioInput' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/inputs/SelectInput' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/inputs/TextAreaInput' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/inputs/TextInput' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/inputs/TimePickerInput' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/MetamaskPage' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/Navbar' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/ProgressBar' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/Remark' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/Sidebar' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/STOStatus' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/helpers' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/index' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/modules/account/actions' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/modules/account/EnterPINForm' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/modules/account/EnterPINModal' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/modules/account/reducer' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/modules/account/SignInPage' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/modules/account/SignUpForm' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/modules/account/SignUpPage' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/modules/account/SignUpSuccessPage' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/modules/modal/actions' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/modules/modal/ConfirmModal' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/modules/modal/reducer' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/modules/notice/actions' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/modules/notice/NoticeBar' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/modules/notice/reducer' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/modules/toaster/actions' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/modules/toaster/reducer' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/modules/toaster/Toaster' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/modules/tx/__tests__/actions.test' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/modules/tx/actions' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/modules/tx/reducer' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/modules/tx/TxModal' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/offchain' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/PolymathUI' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/redux/common/actions' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/redux/common/reducer' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/redux/helpers' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/redux/reducer' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/specsInit' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/svg/briefcase' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/svg/handshake' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/svg/help' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/svg/inbox' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/svg/paper-plane' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/svg/whitelist' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/validate' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/webpack.dev' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/webpack.prod' {
  declare module.exports: any;
}

// Filename aliases
declare module '@polymathnetwork/ui/babel.config.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/babel.config'>;
}
declare module '@polymathnetwork/ui/jest.config.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/jest.config'>;
}
declare module '@polymathnetwork/ui/src/components/Countdown.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/Countdown'
  >;
}
declare module '@polymathnetwork/ui/src/components/DummyPage.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/DummyPage'
  >;
}
declare module '@polymathnetwork/ui/src/components/Footer.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/src/components/Footer'>;
}
declare module '@polymathnetwork/ui/src/components/inputs/CheckboxInput.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/inputs/CheckboxInput'
  >;
}
declare module '@polymathnetwork/ui/src/components/inputs/DatePickerInput.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/inputs/DatePickerInput'
  >;
}
declare module '@polymathnetwork/ui/src/components/inputs/DatePickerRangeInput.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/inputs/DatePickerRangeInput'
  >;
}
declare module '@polymathnetwork/ui/src/components/inputs/RadioInput.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/inputs/RadioInput'
  >;
}
declare module '@polymathnetwork/ui/src/components/inputs/SelectInput.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/inputs/SelectInput'
  >;
}
declare module '@polymathnetwork/ui/src/components/inputs/TextAreaInput.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/inputs/TextAreaInput'
  >;
}
declare module '@polymathnetwork/ui/src/components/inputs/TextInput.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/inputs/TextInput'
  >;
}
declare module '@polymathnetwork/ui/src/components/inputs/TimePickerInput.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/inputs/TimePickerInput'
  >;
}
declare module '@polymathnetwork/ui/src/components/MetamaskPage.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/MetamaskPage'
  >;
}
declare module '@polymathnetwork/ui/src/components/Navbar.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/src/components/Navbar'>;
}
declare module '@polymathnetwork/ui/src/components/ProgressBar.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/ProgressBar'
  >;
}
declare module '@polymathnetwork/ui/src/components/Remark.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/src/components/Remark'>;
}
declare module '@polymathnetwork/ui/src/components/Sidebar.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/Sidebar'
  >;
}
declare module '@polymathnetwork/ui/src/components/STOStatus.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/STOStatus'
  >;
}
declare module '@polymathnetwork/ui/src/helpers.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/src/helpers'>;
}
declare module '@polymathnetwork/ui/src/index.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/src/index'>;
}
declare module '@polymathnetwork/ui/src/modules/account/actions.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/modules/account/actions'
  >;
}
declare module '@polymathnetwork/ui/src/modules/account/EnterPINForm.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/modules/account/EnterPINForm'
  >;
}
declare module '@polymathnetwork/ui/src/modules/account/EnterPINModal.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/modules/account/EnterPINModal'
  >;
}
declare module '@polymathnetwork/ui/src/modules/account/reducer.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/modules/account/reducer'
  >;
}
declare module '@polymathnetwork/ui/src/modules/account/SignInPage.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/modules/account/SignInPage'
  >;
}
declare module '@polymathnetwork/ui/src/modules/account/SignUpForm.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/modules/account/SignUpForm'
  >;
}
declare module '@polymathnetwork/ui/src/modules/account/SignUpPage.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/modules/account/SignUpPage'
  >;
}
declare module '@polymathnetwork/ui/src/modules/account/SignUpSuccessPage.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/modules/account/SignUpSuccessPage'
  >;
}
declare module '@polymathnetwork/ui/src/modules/modal/actions.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/modules/modal/actions'
  >;
}
declare module '@polymathnetwork/ui/src/modules/modal/ConfirmModal.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/modules/modal/ConfirmModal'
  >;
}
declare module '@polymathnetwork/ui/src/modules/modal/reducer.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/modules/modal/reducer'
  >;
}
declare module '@polymathnetwork/ui/src/modules/notice/actions.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/modules/notice/actions'
  >;
}
declare module '@polymathnetwork/ui/src/modules/notice/NoticeBar.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/modules/notice/NoticeBar'
  >;
}
declare module '@polymathnetwork/ui/src/modules/notice/reducer.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/modules/notice/reducer'
  >;
}
declare module '@polymathnetwork/ui/src/modules/toaster/actions.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/modules/toaster/actions'
  >;
}
declare module '@polymathnetwork/ui/src/modules/toaster/reducer.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/modules/toaster/reducer'
  >;
}
declare module '@polymathnetwork/ui/src/modules/toaster/Toaster.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/modules/toaster/Toaster'
  >;
}
declare module '@polymathnetwork/ui/src/modules/tx/__tests__/actions.test.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/modules/tx/__tests__/actions.test'
  >;
}
declare module '@polymathnetwork/ui/src/modules/tx/actions.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/modules/tx/actions'
  >;
}
declare module '@polymathnetwork/ui/src/modules/tx/reducer.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/modules/tx/reducer'
  >;
}
declare module '@polymathnetwork/ui/src/modules/tx/TxModal.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/modules/tx/TxModal'
  >;
}
declare module '@polymathnetwork/ui/src/offchain.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/src/offchain'>;
}
declare module '@polymathnetwork/ui/src/PolymathUI.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/src/PolymathUI'>;
}
declare module '@polymathnetwork/ui/src/redux/common/actions.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/redux/common/actions'
  >;
}
declare module '@polymathnetwork/ui/src/redux/common/reducer.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/redux/common/reducer'
  >;
}
declare module '@polymathnetwork/ui/src/redux/helpers.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/src/redux/helpers'>;
}
declare module '@polymathnetwork/ui/src/redux/reducer.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/src/redux/reducer'>;
}
declare module '@polymathnetwork/ui/src/specsInit.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/src/specsInit'>;
}
declare module '@polymathnetwork/ui/src/svg/briefcase.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/src/svg/briefcase'>;
}
declare module '@polymathnetwork/ui/src/svg/handshake.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/src/svg/handshake'>;
}
declare module '@polymathnetwork/ui/src/svg/help.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/src/svg/help'>;
}
declare module '@polymathnetwork/ui/src/svg/inbox.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/src/svg/inbox'>;
}
declare module '@polymathnetwork/ui/src/svg/paper-plane.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/src/svg/paper-plane'>;
}
declare module '@polymathnetwork/ui/src/svg/whitelist.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/src/svg/whitelist'>;
}
declare module '@polymathnetwork/ui/src/validate.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/src/validate'>;
}
declare module '@polymathnetwork/ui/webpack.dev.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/webpack.dev'>;
}
declare module '@polymathnetwork/ui/webpack.prod.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/webpack.prod'>;
}
