// flow-typed signature: 05cb78a3a840ec80faeec34e40d51205
// flow-typed version: <<STUB>>/carbon-icons_v^7.0.7/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'carbon-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'carbon-icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'carbon-icons/dist/carbon-icons-list' {
  declare module.exports: any;
}

declare module 'carbon-icons/dist/carbon-icons.es' {
  declare module.exports: any;
}

declare module 'carbon-icons/dist/carbon-icons' {
  declare module.exports: any;
}

// Filename aliases
declare module 'carbon-icons/dist/carbon-icons-list.js' {
  declare module.exports: $Exports<'carbon-icons/dist/carbon-icons-list'>;
}
declare module 'carbon-icons/dist/carbon-icons.es.js' {
  declare module.exports: $Exports<'carbon-icons/dist/carbon-icons.es'>;
}
declare module 'carbon-icons/dist/carbon-icons.js' {
  declare module.exports: $Exports<'carbon-icons/dist/carbon-icons'>;
}
