// flow-typed signature: eed881e8bf97ab3e58d3c1e5b9b6f285
// flow-typed version: <<STUB>>/ddos_v^0.1.30/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ddos'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ddos' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ddos/lib/defaults' {
  declare module.exports: any;
}

declare module 'ddos/lib/index' {
  declare module.exports: any;
}

declare module 'ddos/lib/koa' {
  declare module.exports: any;
}

declare module 'ddos/test/test-express' {
  declare module.exports: any;
}

declare module 'ddos/test/test-hapi' {
  declare module.exports: any;
}

declare module 'ddos/test/test-koa' {
  declare module.exports: any;
}

declare module 'ddos/test/test-maxcount' {
  declare module.exports: any;
}

declare module 'ddos/test/test-options' {
  declare module.exports: any;
}

declare module 'ddos/test/test-post' {
  declare module.exports: any;
}

declare module 'ddos/test/test-stop' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ddos/index' {
  declare module.exports: $Exports<'ddos'>;
}
declare module 'ddos/index.js' {
  declare module.exports: $Exports<'ddos'>;
}
declare module 'ddos/lib/defaults.js' {
  declare module.exports: $Exports<'ddos/lib/defaults'>;
}
declare module 'ddos/lib/index.js' {
  declare module.exports: $Exports<'ddos/lib/index'>;
}
declare module 'ddos/lib/koa.js' {
  declare module.exports: $Exports<'ddos/lib/koa'>;
}
declare module 'ddos/test/test-express.js' {
  declare module.exports: $Exports<'ddos/test/test-express'>;
}
declare module 'ddos/test/test-hapi.js' {
  declare module.exports: $Exports<'ddos/test/test-hapi'>;
}
declare module 'ddos/test/test-koa.js' {
  declare module.exports: $Exports<'ddos/test/test-koa'>;
}
declare module 'ddos/test/test-maxcount.js' {
  declare module.exports: $Exports<'ddos/test/test-maxcount'>;
}
declare module 'ddos/test/test-options.js' {
  declare module.exports: $Exports<'ddos/test/test-options'>;
}
declare module 'ddos/test/test-post.js' {
  declare module.exports: $Exports<'ddos/test/test-post'>;
}
declare module 'ddos/test/test-stop.js' {
  declare module.exports: $Exports<'ddos/test/test-stop'>;
}
