// flow-typed signature: 26b2400f0c49f675286f97f03bb8364d
// flow-typed version: <<STUB>>/eslint-config-react-app_v2.1.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-react-app'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-react-app' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'eslint-config-react-app/index' {
  declare module.exports: $Exports<'eslint-config-react-app'>;
}
declare module 'eslint-config-react-app/index.js' {
  declare module.exports: $Exports<'eslint-config-react-app'>;
}
