// flow-typed signature: 7b8a3ba26acc64a3254dbc058531c663
// flow-typed version: <<STUB>>/eth-sig-util_v^1.4.2/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eth-sig-util'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eth-sig-util' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eth-sig-util/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eth-sig-util/index' {
  declare module.exports: $Exports<'eth-sig-util'>;
}
declare module 'eth-sig-util/index.js' {
  declare module.exports: $Exports<'eth-sig-util'>;
}
declare module 'eth-sig-util/test/index.js' {
  declare module.exports: $Exports<'eth-sig-util/test/index'>;
}
