// flow-typed signature: 3819007f692d75e31ab222728f5bbc2a
// flow-typed version: <<STUB>>/polymath-core_v1.4.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'polymath-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'polymath-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'polymath-core/CLI/commands/accredit' {
  declare module.exports: any;
}

declare module 'polymath-core/CLI/commands/checkpoint/erc20Explorer' {
  declare module.exports: any;
}

declare module 'polymath-core/CLI/commands/checkpoint/ethExplorer' {
  declare module.exports: any;
}

declare module 'polymath-core/CLI/commands/common/common_functions' {
  declare module.exports: any;
}

declare module 'polymath-core/CLI/commands/faucet' {
  declare module.exports: any;
}

declare module 'polymath-core/CLI/commands/helpers/contract_abis' {
  declare module.exports: any;
}

declare module 'polymath-core/CLI/commands/helpers/contract_addresses' {
  declare module.exports: any;
}

declare module 'polymath-core/CLI/commands/investor_portal' {
  declare module.exports: any;
}

declare module 'polymath-core/CLI/commands/module_manager' {
  declare module.exports: any;
}

declare module 'polymath-core/CLI/commands/multi_mint' {
  declare module.exports: any;
}

declare module 'polymath-core/CLI/commands/ST20Generator' {
  declare module.exports: any;
}

declare module 'polymath-core/CLI/commands/strMigrator' {
  declare module.exports: any;
}

declare module 'polymath-core/CLI/commands/TickerRollForward' {
  declare module.exports: any;
}

declare module 'polymath-core/CLI/commands/transfer' {
  declare module.exports: any;
}

declare module 'polymath-core/CLI/commands/whitelist' {
  declare module.exports: any;
}

declare module 'polymath-core/CLI/polymath-cli' {
  declare module.exports: any;
}

declare module 'polymath-core/migrations/1_deploy_token' {
  declare module.exports: any;
}

declare module 'polymath-core/migrations/2_deploy_contracts' {
  declare module.exports: any;
}

declare module 'polymath-core/scripts/encoders/encode_CappedSTO' {
  declare module.exports: any;
}

declare module 'polymath-core/test/a_poly_oracle' {
  declare module.exports: any;
}

declare module 'polymath-core/test/b_capped_sto' {
  declare module.exports: any;
}

declare module 'polymath-core/test/c_checkpoints' {
  declare module.exports: any;
}

declare module 'polymath-core/test/d_count_transfer_manager' {
  declare module.exports: any;
}

declare module 'polymath-core/test/e_erc20_dividends' {
  declare module.exports: any;
}

declare module 'polymath-core/test/f_ether_dividends' {
  declare module.exports: any;
}

declare module 'polymath-core/test/g_general_permission_manager' {
  declare module.exports: any;
}

declare module 'polymath-core/test/h_general_transfer_manager' {
  declare module.exports: any;
}

declare module 'polymath-core/test/helpers/latestTime' {
  declare module.exports: any;
}

declare module 'polymath-core/test/helpers/signData' {
  declare module.exports: any;
}

declare module 'polymath-core/test/helpers/testprivateKey' {
  declare module.exports: any;
}

declare module 'polymath-core/test/helpers/time' {
  declare module.exports: any;
}

declare module 'polymath-core/test/helpers/utils' {
  declare module.exports: any;
}

declare module 'polymath-core/test/i_Issuance' {
  declare module.exports: any;
}

declare module 'polymath-core/test/j_manual_approval_transfer_manager' {
  declare module.exports: any;
}

declare module 'polymath-core/test/k_module_registry' {
  declare module.exports: any;
}

declare module 'polymath-core/test/l_percentage_transfer_manager' {
  declare module.exports: any;
}

declare module 'polymath-core/test/m_presale_sto' {
  declare module.exports: any;
}

declare module 'polymath-core/test/n_security_token_registry' {
  declare module.exports: any;
}

declare module 'polymath-core/test/o_security_token' {
  declare module.exports: any;
}

declare module 'polymath-core/test/p_ticker_registry' {
  declare module.exports: any;
}

declare module 'polymath-core/test/q_usd_tiered_sto' {
  declare module.exports: any;
}

declare module 'polymath-core/test/r_usd_tiered_sto_sim' {
  declare module.exports: any;
}

declare module 'polymath-core/test/s_concurrent_STO' {
  declare module.exports: any;
}

declare module 'polymath-core/test/t_v130_to_v140_upgrade' {
  declare module.exports: any;
}

declare module 'polymath-core/truffle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'polymath-core/CLI/commands/accredit.js' {
  declare module.exports: $Exports<'polymath-core/CLI/commands/accredit'>;
}
declare module 'polymath-core/CLI/commands/checkpoint/erc20Explorer.js' {
  declare module.exports: $Exports<
    'polymath-core/CLI/commands/checkpoint/erc20Explorer'
  >;
}
declare module 'polymath-core/CLI/commands/checkpoint/ethExplorer.js' {
  declare module.exports: $Exports<
    'polymath-core/CLI/commands/checkpoint/ethExplorer'
  >;
}
declare module 'polymath-core/CLI/commands/common/common_functions.js' {
  declare module.exports: $Exports<
    'polymath-core/CLI/commands/common/common_functions'
  >;
}
declare module 'polymath-core/CLI/commands/faucet.js' {
  declare module.exports: $Exports<'polymath-core/CLI/commands/faucet'>;
}
declare module 'polymath-core/CLI/commands/helpers/contract_abis.js' {
  declare module.exports: $Exports<
    'polymath-core/CLI/commands/helpers/contract_abis'
  >;
}
declare module 'polymath-core/CLI/commands/helpers/contract_addresses.js' {
  declare module.exports: $Exports<
    'polymath-core/CLI/commands/helpers/contract_addresses'
  >;
}
declare module 'polymath-core/CLI/commands/investor_portal.js' {
  declare module.exports: $Exports<
    'polymath-core/CLI/commands/investor_portal'
  >;
}
declare module 'polymath-core/CLI/commands/module_manager.js' {
  declare module.exports: $Exports<'polymath-core/CLI/commands/module_manager'>;
}
declare module 'polymath-core/CLI/commands/multi_mint.js' {
  declare module.exports: $Exports<'polymath-core/CLI/commands/multi_mint'>;
}
declare module 'polymath-core/CLI/commands/ST20Generator.js' {
  declare module.exports: $Exports<'polymath-core/CLI/commands/ST20Generator'>;
}
declare module 'polymath-core/CLI/commands/strMigrator.js' {
  declare module.exports: $Exports<'polymath-core/CLI/commands/strMigrator'>;
}
declare module 'polymath-core/CLI/commands/TickerRollForward.js' {
  declare module.exports: $Exports<
    'polymath-core/CLI/commands/TickerRollForward'
  >;
}
declare module 'polymath-core/CLI/commands/transfer.js' {
  declare module.exports: $Exports<'polymath-core/CLI/commands/transfer'>;
}
declare module 'polymath-core/CLI/commands/whitelist.js' {
  declare module.exports: $Exports<'polymath-core/CLI/commands/whitelist'>;
}
declare module 'polymath-core/CLI/polymath-cli.js' {
  declare module.exports: $Exports<'polymath-core/CLI/polymath-cli'>;
}
declare module 'polymath-core/migrations/1_deploy_token.js' {
  declare module.exports: $Exports<'polymath-core/migrations/1_deploy_token'>;
}
declare module 'polymath-core/migrations/2_deploy_contracts.js' {
  declare module.exports: $Exports<
    'polymath-core/migrations/2_deploy_contracts'
  >;
}
declare module 'polymath-core/scripts/encoders/encode_CappedSTO.js' {
  declare module.exports: $Exports<
    'polymath-core/scripts/encoders/encode_CappedSTO'
  >;
}
declare module 'polymath-core/test/a_poly_oracle.js' {
  declare module.exports: $Exports<'polymath-core/test/a_poly_oracle'>;
}
declare module 'polymath-core/test/b_capped_sto.js' {
  declare module.exports: $Exports<'polymath-core/test/b_capped_sto'>;
}
declare module 'polymath-core/test/c_checkpoints.js' {
  declare module.exports: $Exports<'polymath-core/test/c_checkpoints'>;
}
declare module 'polymath-core/test/d_count_transfer_manager.js' {
  declare module.exports: $Exports<
    'polymath-core/test/d_count_transfer_manager'
  >;
}
declare module 'polymath-core/test/e_erc20_dividends.js' {
  declare module.exports: $Exports<'polymath-core/test/e_erc20_dividends'>;
}
declare module 'polymath-core/test/f_ether_dividends.js' {
  declare module.exports: $Exports<'polymath-core/test/f_ether_dividends'>;
}
declare module 'polymath-core/test/g_general_permission_manager.js' {
  declare module.exports: $Exports<
    'polymath-core/test/g_general_permission_manager'
  >;
}
declare module 'polymath-core/test/h_general_transfer_manager.js' {
  declare module.exports: $Exports<
    'polymath-core/test/h_general_transfer_manager'
  >;
}
declare module 'polymath-core/test/helpers/latestTime.js' {
  declare module.exports: $Exports<'polymath-core/test/helpers/latestTime'>;
}
declare module 'polymath-core/test/helpers/signData.js' {
  declare module.exports: $Exports<'polymath-core/test/helpers/signData'>;
}
declare module 'polymath-core/test/helpers/testprivateKey.js' {
  declare module.exports: $Exports<'polymath-core/test/helpers/testprivateKey'>;
}
declare module 'polymath-core/test/helpers/time.js' {
  declare module.exports: $Exports<'polymath-core/test/helpers/time'>;
}
declare module 'polymath-core/test/helpers/utils.js' {
  declare module.exports: $Exports<'polymath-core/test/helpers/utils'>;
}
declare module 'polymath-core/test/i_Issuance.js' {
  declare module.exports: $Exports<'polymath-core/test/i_Issuance'>;
}
declare module 'polymath-core/test/j_manual_approval_transfer_manager.js' {
  declare module.exports: $Exports<
    'polymath-core/test/j_manual_approval_transfer_manager'
  >;
}
declare module 'polymath-core/test/k_module_registry.js' {
  declare module.exports: $Exports<'polymath-core/test/k_module_registry'>;
}
declare module 'polymath-core/test/l_percentage_transfer_manager.js' {
  declare module.exports: $Exports<
    'polymath-core/test/l_percentage_transfer_manager'
  >;
}
declare module 'polymath-core/test/m_presale_sto.js' {
  declare module.exports: $Exports<'polymath-core/test/m_presale_sto'>;
}
declare module 'polymath-core/test/n_security_token_registry.js' {
  declare module.exports: $Exports<
    'polymath-core/test/n_security_token_registry'
  >;
}
declare module 'polymath-core/test/o_security_token.js' {
  declare module.exports: $Exports<'polymath-core/test/o_security_token'>;
}
declare module 'polymath-core/test/p_ticker_registry.js' {
  declare module.exports: $Exports<'polymath-core/test/p_ticker_registry'>;
}
declare module 'polymath-core/test/q_usd_tiered_sto.js' {
  declare module.exports: $Exports<'polymath-core/test/q_usd_tiered_sto'>;
}
declare module 'polymath-core/test/r_usd_tiered_sto_sim.js' {
  declare module.exports: $Exports<'polymath-core/test/r_usd_tiered_sto_sim'>;
}
declare module 'polymath-core/test/s_concurrent_STO.js' {
  declare module.exports: $Exports<'polymath-core/test/s_concurrent_STO'>;
}
declare module 'polymath-core/test/t_v130_to_v140_upgrade.js' {
  declare module.exports: $Exports<'polymath-core/test/t_v130_to_v140_upgrade'>;
}
declare module 'polymath-core/truffle.js' {
  declare module.exports: $Exports<'polymath-core/truffle'>;
}
