// flow-typed signature: 4ddbb055c3ad494116a701a5619791ce
// flow-typed version: <<STUB>>/react-dropzone_v^5.1.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dropzone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dropzone' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dropzone/commitlint.config' {
  declare module.exports: any;
}

declare module 'react-dropzone/dist/es/index' {
  declare module.exports: any;
}

declare module 'react-dropzone/dist/es/utils/index' {
  declare module.exports: any;
}

declare module 'react-dropzone/dist/es/utils/styles' {
  declare module.exports: any;
}

declare module 'react-dropzone/dist/index' {
  declare module.exports: any;
}

declare module 'react-dropzone/rollup.config' {
  declare module.exports: any;
}

declare module 'react-dropzone/src/index' {
  declare module.exports: any;
}

declare module 'react-dropzone/src/index.spec' {
  declare module.exports: any;
}

declare module 'react-dropzone/src/utils/index' {
  declare module.exports: any;
}

declare module 'react-dropzone/src/utils/index.spec' {
  declare module.exports: any;
}

declare module 'react-dropzone/src/utils/styles' {
  declare module.exports: any;
}

declare module 'react-dropzone/styleguide.config' {
  declare module.exports: any;
}

declare module 'react-dropzone/testSetup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dropzone/commitlint.config.js' {
  declare module.exports: $Exports<'react-dropzone/commitlint.config'>;
}
declare module 'react-dropzone/dist/es/index.js' {
  declare module.exports: $Exports<'react-dropzone/dist/es/index'>;
}
declare module 'react-dropzone/dist/es/utils/index.js' {
  declare module.exports: $Exports<'react-dropzone/dist/es/utils/index'>;
}
declare module 'react-dropzone/dist/es/utils/styles.js' {
  declare module.exports: $Exports<'react-dropzone/dist/es/utils/styles'>;
}
declare module 'react-dropzone/dist/index.js' {
  declare module.exports: $Exports<'react-dropzone/dist/index'>;
}
declare module 'react-dropzone/rollup.config.js' {
  declare module.exports: $Exports<'react-dropzone/rollup.config'>;
}
declare module 'react-dropzone/src/index.js' {
  declare module.exports: $Exports<'react-dropzone/src/index'>;
}
declare module 'react-dropzone/src/index.spec.js' {
  declare module.exports: $Exports<'react-dropzone/src/index.spec'>;
}
declare module 'react-dropzone/src/utils/index.js' {
  declare module.exports: $Exports<'react-dropzone/src/utils/index'>;
}
declare module 'react-dropzone/src/utils/index.spec.js' {
  declare module.exports: $Exports<'react-dropzone/src/utils/index.spec'>;
}
declare module 'react-dropzone/src/utils/styles.js' {
  declare module.exports: $Exports<'react-dropzone/src/utils/styles'>;
}
declare module 'react-dropzone/styleguide.config.js' {
  declare module.exports: $Exports<'react-dropzone/styleguide.config'>;
}
declare module 'react-dropzone/testSetup.js' {
  declare module.exports: $Exports<'react-dropzone/testSetup'>;
}
