// flow-typed signature: ebaa6de5186b7780234aa39ddaeadc86
// flow-typed version: <<STUB>>/@polymathnetwork/js_v0.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@polymathnetwork/js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@polymathnetwork/js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@polymathnetwork/js/babel.config' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/flow-typed/npm/@babel/cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/flow-typed/npm/@babel/core_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/flow-typed/npm/@babel/node_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/flow-typed/npm/@babel/plugin-proposal-export-default-from_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/flow-typed/npm/@babel/plugin-proposal-object-rest-spread_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/flow-typed/npm/@babel/plugin-transform-react-jsx_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/flow-typed/npm/@babel/preset-env_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/flow-typed/npm/@babel/preset-flow_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/flow-typed/npm/@babel/runtime-corejs2_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/flow-typed/npm/@polymathnetwork/shared_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/flow-typed/npm/bignumber.js_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/flow-typed/npm/bs58_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/flow-typed/npm/husky_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/flow-typed/npm/jest_v22.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/flow-typed/npm/polymath-core_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/flow-typed/npm/redux_v3.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/flow-typed/npm/redux-thunk_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/flow-typed/npm/web3_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/flow-typed/npm/webpack_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/flow-typed/npm/webpack-cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/src/contracts/CappedSTOFactory' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/src/contracts/Contract' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/src/contracts/CountTransferManager' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/src/contracts/CountTransferManagerFactory' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/src/contracts/IModuleFactory' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/src/contracts/PercentageTransferManager' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/src/contracts/PercentageTransferManagerFactory' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/src/contracts/PermissionManager' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/src/contracts/PolyToken' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/src/contracts/SecurityToken' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/src/contracts/SecurityTokenRegistry' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/src/contracts/STO' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/src/contracts/TickerRegistry' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/src/contracts/TransferManager' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/src/index' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/src/IPFS' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/src/types' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/webpack.dev' {
  declare module.exports: any;
}

declare module '@polymathnetwork/js/webpack.prod' {
  declare module.exports: any;
}

// Filename aliases
declare module '@polymathnetwork/js/babel.config.js' {
  declare module.exports: $Exports<'@polymathnetwork/js/babel.config'>;
}
declare module '@polymathnetwork/js/flow-typed/npm/@babel/cli_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/flow-typed/npm/@babel/cli_vx.x.x'
  >;
}
declare module '@polymathnetwork/js/flow-typed/npm/@babel/core_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/flow-typed/npm/@babel/core_vx.x.x'
  >;
}
declare module '@polymathnetwork/js/flow-typed/npm/@babel/node_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/flow-typed/npm/@babel/node_vx.x.x'
  >;
}
declare module '@polymathnetwork/js/flow-typed/npm/@babel/plugin-proposal-export-default-from_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/flow-typed/npm/@babel/plugin-proposal-export-default-from_vx.x.x'
  >;
}
declare module '@polymathnetwork/js/flow-typed/npm/@babel/plugin-proposal-object-rest-spread_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/flow-typed/npm/@babel/plugin-proposal-object-rest-spread_vx.x.x'
  >;
}
declare module '@polymathnetwork/js/flow-typed/npm/@babel/plugin-transform-react-jsx_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/flow-typed/npm/@babel/plugin-transform-react-jsx_vx.x.x'
  >;
}
declare module '@polymathnetwork/js/flow-typed/npm/@babel/preset-env_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/flow-typed/npm/@babel/preset-env_vx.x.x'
  >;
}
declare module '@polymathnetwork/js/flow-typed/npm/@babel/preset-flow_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/flow-typed/npm/@babel/preset-flow_vx.x.x'
  >;
}
declare module '@polymathnetwork/js/flow-typed/npm/@babel/runtime-corejs2_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/flow-typed/npm/@babel/runtime-corejs2_vx.x.x'
  >;
}
declare module '@polymathnetwork/js/flow-typed/npm/@polymathnetwork/shared_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/flow-typed/npm/@polymathnetwork/shared_vx.x.x'
  >;
}
declare module '@polymathnetwork/js/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/flow-typed/npm/babel-core_vx.x.x'
  >;
}
declare module '@polymathnetwork/js/flow-typed/npm/bignumber.js_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/flow-typed/npm/bignumber.js_vx.x.x'
  >;
}
declare module '@polymathnetwork/js/flow-typed/npm/bs58_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/flow-typed/npm/bs58_vx.x.x'
  >;
}
declare module '@polymathnetwork/js/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/flow-typed/npm/flow-bin_v0.x.x'
  >;
}
declare module '@polymathnetwork/js/flow-typed/npm/husky_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/flow-typed/npm/husky_vx.x.x'
  >;
}
declare module '@polymathnetwork/js/flow-typed/npm/jest_v22.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/flow-typed/npm/jest_v22.x.x'
  >;
}
declare module '@polymathnetwork/js/flow-typed/npm/polymath-core_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/flow-typed/npm/polymath-core_vx.x.x'
  >;
}
declare module '@polymathnetwork/js/flow-typed/npm/redux_v3.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/flow-typed/npm/redux_v3.x.x'
  >;
}
declare module '@polymathnetwork/js/flow-typed/npm/redux-thunk_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/flow-typed/npm/redux-thunk_vx.x.x'
  >;
}
declare module '@polymathnetwork/js/flow-typed/npm/web3_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/flow-typed/npm/web3_vx.x.x'
  >;
}
declare module '@polymathnetwork/js/flow-typed/npm/webpack_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/flow-typed/npm/webpack_vx.x.x'
  >;
}
declare module '@polymathnetwork/js/flow-typed/npm/webpack-cli_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/flow-typed/npm/webpack-cli_vx.x.x'
  >;
}
declare module '@polymathnetwork/js/src/contracts/CappedSTOFactory.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/src/contracts/CappedSTOFactory'
  >;
}
declare module '@polymathnetwork/js/src/contracts/Contract.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/src/contracts/Contract'
  >;
}
declare module '@polymathnetwork/js/src/contracts/CountTransferManager.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/src/contracts/CountTransferManager'
  >;
}
declare module '@polymathnetwork/js/src/contracts/CountTransferManagerFactory.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/src/contracts/CountTransferManagerFactory'
  >;
}
declare module '@polymathnetwork/js/src/contracts/IModuleFactory.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/src/contracts/IModuleFactory'
  >;
}
declare module '@polymathnetwork/js/src/contracts/PercentageTransferManager.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/src/contracts/PercentageTransferManager'
  >;
}
declare module '@polymathnetwork/js/src/contracts/PercentageTransferManagerFactory.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/src/contracts/PercentageTransferManagerFactory'
  >;
}
declare module '@polymathnetwork/js/src/contracts/PermissionManager.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/src/contracts/PermissionManager'
  >;
}
declare module '@polymathnetwork/js/src/contracts/PolyToken.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/src/contracts/PolyToken'
  >;
}
declare module '@polymathnetwork/js/src/contracts/SecurityToken.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/src/contracts/SecurityToken'
  >;
}
declare module '@polymathnetwork/js/src/contracts/SecurityTokenRegistry.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/src/contracts/SecurityTokenRegistry'
  >;
}
declare module '@polymathnetwork/js/src/contracts/STO.js' {
  declare module.exports: $Exports<'@polymathnetwork/js/src/contracts/STO'>;
}
declare module '@polymathnetwork/js/src/contracts/TickerRegistry.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/src/contracts/TickerRegistry'
  >;
}
declare module '@polymathnetwork/js/src/contracts/TransferManager.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/js/src/contracts/TransferManager'
  >;
}
declare module '@polymathnetwork/js/src/index.js' {
  declare module.exports: $Exports<'@polymathnetwork/js/src/index'>;
}
declare module '@polymathnetwork/js/src/IPFS.js' {
  declare module.exports: $Exports<'@polymathnetwork/js/src/IPFS'>;
}
declare module '@polymathnetwork/js/src/types.js' {
  declare module.exports: $Exports<'@polymathnetwork/js/src/types'>;
}
declare module '@polymathnetwork/js/webpack.dev.js' {
  declare module.exports: $Exports<'@polymathnetwork/js/webpack.dev'>;
}
declare module '@polymathnetwork/js/webpack.prod.js' {
  declare module.exports: $Exports<'@polymathnetwork/js/webpack.prod'>;
}
