// flow-typed signature: be635c460ed212fc265fe1f7455caf50
// flow-typed version: <<STUB>>/@polymathnetwork/ui_v0.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@polymathnetwork/ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@polymathnetwork/ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@polymathnetwork/ui/babel.config' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/build/main' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/@babel/cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/@babel/core_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/@babel/node_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/@babel/plugin-proposal-export-default-from_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/@babel/plugin-proposal-object-rest-spread_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/@babel/plugin-transform-react-jsx_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/@babel/preset-env_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/@babel/preset-flow_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/@babel/preset-react_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/@babel/runtime_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/@polymathnetwork/js_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/axios_v0.18.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/babel-jest_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/bignumber.js_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/carbon-components_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/carbon-components-react_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/carbon-icons_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/css-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/docz_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/enzyme_v3.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/enzyme-adapter-react-15_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/enzyme-adapter-react-16_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/eth-sig-util_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/husky_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/jest_v22.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/node-sass_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/react-document-title_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/react-measure_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/react-redux_v5.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/react-router-dom_v4.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/react-test-renderer_v16.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/react-transition-group_v2.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/redux_v4.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/redux-mock-store_v1.2.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/redux-thunk_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/regenerator-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/sass-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/style-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/webpack_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/flow-typed/npm/webpack-cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/jest.config' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/ConfirmModal/actions' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/ConfirmModal/ConfirmModal' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/ConfirmModal/index' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/ConfirmModal/reducer' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/Countdown/Countdown' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/Countdown/index' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/EnterPINForm' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/EnterPINModal' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/EthNetworkWrapper/actions' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/EthNetworkWrapper/EthNetworkWrapper' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/EthNetworkWrapper/helpers' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/EthNetworkWrapper/index' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/EthNetworkWrapper/networks' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/EthNetworkWrapper/reducer' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/Footer/Footer' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/Footer/index' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/inputs/CheckboxInput' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/inputs/DatePickerInput' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/inputs/DatePickerRangeInput' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/inputs/RadioInput' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/inputs/SelectInput' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/inputs/TextAreaInput' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/inputs/TextInput' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/inputs/TimePickerInput' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/MetamaskStatus/index' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/MetamaskStatus/MetamaskStatus' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/Navbar/index' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/Navbar/Navbar' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/NotFoundPage/index' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/NotFoundPage/NotFoundPage' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/NoticeBar/actions' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/NoticeBar/index' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/NoticeBar/NoticeBar' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/NoticeBar/reducer' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/NotSupportedPage/index' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/NotSupportedPage/NotSupportedPage' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/PausedBar/index' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/PausedBar/PausedBar' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/ProgressBar/index' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/ProgressBar/ProgressBar' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/Remark/index' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/Remark/Remark' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/Sidebar/index' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/Sidebar/Sidebar' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/SignInPage' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/SignUpForm' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/SignUpPage' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/SignUpSuccessPage' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/STOStatus/index' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/STOStatus/STOStatus' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/Toaster/actions' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/Toaster/index' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/Toaster/reducer' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/Toaster/Toaster' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/TxModal/__tests__/actions.test' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/TxModal/actions' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/TxModal/index' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/TxModal/reducer' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/components/TxModal/TxModal' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/helpers' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/images/svg/briefcase' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/images/svg/handshake' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/images/svg/help' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/images/svg/inbox' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/images/svg/paper-plane' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/images/svg/whitelist' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/index' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/offchain' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/redux/account/actions' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/redux/account/reducer' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/redux/common/actions' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/redux/common/reducer' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/redux/helpers' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/redux/reducer' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/specsInit' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/src/validate' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/webpack.dev' {
  declare module.exports: any;
}

declare module '@polymathnetwork/ui/webpack.prod' {
  declare module.exports: any;
}

// Filename aliases
declare module '@polymathnetwork/ui/babel.config.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/babel.config'>;
}
declare module '@polymathnetwork/ui/build/main.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/build/main'>;
}
declare module '@polymathnetwork/ui/flow-typed/npm/@babel/cli_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/@babel/cli_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/@babel/core_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/@babel/core_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/@babel/node_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/@babel/node_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/@babel/plugin-proposal-export-default-from_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/@babel/plugin-proposal-export-default-from_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/@babel/plugin-proposal-object-rest-spread_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/@babel/plugin-proposal-object-rest-spread_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/@babel/plugin-transform-react-jsx_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/@babel/plugin-transform-react-jsx_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/@babel/preset-env_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/@babel/preset-env_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/@babel/preset-flow_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/@babel/preset-flow_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/@babel/preset-react_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/@babel/preset-react_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/@babel/runtime_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/@babel/runtime_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/@polymathnetwork/js_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/@polymathnetwork/js_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/axios_v0.18.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/axios_v0.18.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/babel-core_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/babel-jest_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/babel-jest_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/bignumber.js_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/bignumber.js_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/carbon-components_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/carbon-components_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/carbon-components-react_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/carbon-components-react_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/carbon-icons_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/carbon-icons_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/css-loader_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/css-loader_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/docz_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/docz_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/enzyme_v3.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/enzyme_v3.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/enzyme-adapter-react-15_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/enzyme-adapter-react-15_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/enzyme-adapter-react-16_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/enzyme-adapter-react-16_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/eslint_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/eth-sig-util_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/eth-sig-util_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/flow-bin_v0.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/husky_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/husky_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/jest_v22.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/jest_v22.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/node-sass_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/node-sass_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/react-document-title_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/react-document-title_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/react-measure_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/react-measure_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/react-redux_v5.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/react-redux_v5.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/react-router-dom_v4.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/react-router-dom_v4.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/react-test-renderer_v16.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/react-test-renderer_v16.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/react-transition-group_v2.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/react-transition-group_v2.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/redux_v4.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/redux_v4.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/redux-mock-store_v1.2.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/redux-mock-store_v1.2.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/redux-thunk_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/redux-thunk_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/regenerator-runtime_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/regenerator-runtime_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/sass-loader_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/sass-loader_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/style-loader_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/style-loader_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/webpack_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/webpack_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/flow-typed/npm/webpack-cli_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/flow-typed/npm/webpack-cli_vx.x.x'
  >;
}
declare module '@polymathnetwork/ui/jest.config.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/jest.config'>;
}
declare module '@polymathnetwork/ui/src/components/ConfirmModal/actions.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/ConfirmModal/actions'
  >;
}
declare module '@polymathnetwork/ui/src/components/ConfirmModal/ConfirmModal.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/ConfirmModal/ConfirmModal'
  >;
}
declare module '@polymathnetwork/ui/src/components/ConfirmModal/index.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/ConfirmModal/index'
  >;
}
declare module '@polymathnetwork/ui/src/components/ConfirmModal/reducer.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/ConfirmModal/reducer'
  >;
}
declare module '@polymathnetwork/ui/src/components/Countdown/Countdown.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/Countdown/Countdown'
  >;
}
declare module '@polymathnetwork/ui/src/components/Countdown/index.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/Countdown/index'
  >;
}
declare module '@polymathnetwork/ui/src/components/EnterPINForm.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/EnterPINForm'
  >;
}
declare module '@polymathnetwork/ui/src/components/EnterPINModal.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/EnterPINModal'
  >;
}
declare module '@polymathnetwork/ui/src/components/EthNetworkWrapper/actions.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/EthNetworkWrapper/actions'
  >;
}
declare module '@polymathnetwork/ui/src/components/EthNetworkWrapper/EthNetworkWrapper.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/EthNetworkWrapper/EthNetworkWrapper'
  >;
}
declare module '@polymathnetwork/ui/src/components/EthNetworkWrapper/helpers.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/EthNetworkWrapper/helpers'
  >;
}
declare module '@polymathnetwork/ui/src/components/EthNetworkWrapper/index.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/EthNetworkWrapper/index'
  >;
}
declare module '@polymathnetwork/ui/src/components/EthNetworkWrapper/networks.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/EthNetworkWrapper/networks'
  >;
}
declare module '@polymathnetwork/ui/src/components/EthNetworkWrapper/reducer.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/EthNetworkWrapper/reducer'
  >;
}
declare module '@polymathnetwork/ui/src/components/Footer/Footer.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/Footer/Footer'
  >;
}
declare module '@polymathnetwork/ui/src/components/Footer/index.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/Footer/index'
  >;
}
declare module '@polymathnetwork/ui/src/components/inputs/CheckboxInput.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/inputs/CheckboxInput'
  >;
}
declare module '@polymathnetwork/ui/src/components/inputs/DatePickerInput.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/inputs/DatePickerInput'
  >;
}
declare module '@polymathnetwork/ui/src/components/inputs/DatePickerRangeInput.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/inputs/DatePickerRangeInput'
  >;
}
declare module '@polymathnetwork/ui/src/components/inputs/RadioInput.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/inputs/RadioInput'
  >;
}
declare module '@polymathnetwork/ui/src/components/inputs/SelectInput.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/inputs/SelectInput'
  >;
}
declare module '@polymathnetwork/ui/src/components/inputs/TextAreaInput.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/inputs/TextAreaInput'
  >;
}
declare module '@polymathnetwork/ui/src/components/inputs/TextInput.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/inputs/TextInput'
  >;
}
declare module '@polymathnetwork/ui/src/components/inputs/TimePickerInput.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/inputs/TimePickerInput'
  >;
}
declare module '@polymathnetwork/ui/src/components/MetamaskStatus/index.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/MetamaskStatus/index'
  >;
}
declare module '@polymathnetwork/ui/src/components/MetamaskStatus/MetamaskStatus.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/MetamaskStatus/MetamaskStatus'
  >;
}
declare module '@polymathnetwork/ui/src/components/Navbar/index.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/Navbar/index'
  >;
}
declare module '@polymathnetwork/ui/src/components/Navbar/Navbar.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/Navbar/Navbar'
  >;
}
declare module '@polymathnetwork/ui/src/components/NotFoundPage/index.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/NotFoundPage/index'
  >;
}
declare module '@polymathnetwork/ui/src/components/NotFoundPage/NotFoundPage.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/NotFoundPage/NotFoundPage'
  >;
}
declare module '@polymathnetwork/ui/src/components/NoticeBar/actions.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/NoticeBar/actions'
  >;
}
declare module '@polymathnetwork/ui/src/components/NoticeBar/index.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/NoticeBar/index'
  >;
}
declare module '@polymathnetwork/ui/src/components/NoticeBar/NoticeBar.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/NoticeBar/NoticeBar'
  >;
}
declare module '@polymathnetwork/ui/src/components/NoticeBar/reducer.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/NoticeBar/reducer'
  >;
}
declare module '@polymathnetwork/ui/src/components/NotSupportedPage/index.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/NotSupportedPage/index'
  >;
}
declare module '@polymathnetwork/ui/src/components/NotSupportedPage/NotSupportedPage.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/NotSupportedPage/NotSupportedPage'
  >;
}
declare module '@polymathnetwork/ui/src/components/PausedBar/index.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/PausedBar/index'
  >;
}
declare module '@polymathnetwork/ui/src/components/PausedBar/PausedBar.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/PausedBar/PausedBar'
  >;
}
declare module '@polymathnetwork/ui/src/components/ProgressBar/index.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/ProgressBar/index'
  >;
}
declare module '@polymathnetwork/ui/src/components/ProgressBar/ProgressBar.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/ProgressBar/ProgressBar'
  >;
}
declare module '@polymathnetwork/ui/src/components/Remark/index.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/Remark/index'
  >;
}
declare module '@polymathnetwork/ui/src/components/Remark/Remark.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/Remark/Remark'
  >;
}
declare module '@polymathnetwork/ui/src/components/Sidebar/index.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/Sidebar/index'
  >;
}
declare module '@polymathnetwork/ui/src/components/Sidebar/Sidebar.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/Sidebar/Sidebar'
  >;
}
declare module '@polymathnetwork/ui/src/components/SignInPage.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/SignInPage'
  >;
}
declare module '@polymathnetwork/ui/src/components/SignUpForm.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/SignUpForm'
  >;
}
declare module '@polymathnetwork/ui/src/components/SignUpPage.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/SignUpPage'
  >;
}
declare module '@polymathnetwork/ui/src/components/SignUpSuccessPage.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/SignUpSuccessPage'
  >;
}
declare module '@polymathnetwork/ui/src/components/STOStatus/index.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/STOStatus/index'
  >;
}
declare module '@polymathnetwork/ui/src/components/STOStatus/STOStatus.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/STOStatus/STOStatus'
  >;
}
declare module '@polymathnetwork/ui/src/components/Toaster/actions.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/Toaster/actions'
  >;
}
declare module '@polymathnetwork/ui/src/components/Toaster/index.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/Toaster/index'
  >;
}
declare module '@polymathnetwork/ui/src/components/Toaster/reducer.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/Toaster/reducer'
  >;
}
declare module '@polymathnetwork/ui/src/components/Toaster/Toaster.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/Toaster/Toaster'
  >;
}
declare module '@polymathnetwork/ui/src/components/TxModal/__tests__/actions.test.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/TxModal/__tests__/actions.test'
  >;
}
declare module '@polymathnetwork/ui/src/components/TxModal/actions.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/TxModal/actions'
  >;
}
declare module '@polymathnetwork/ui/src/components/TxModal/index.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/TxModal/index'
  >;
}
declare module '@polymathnetwork/ui/src/components/TxModal/reducer.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/TxModal/reducer'
  >;
}
declare module '@polymathnetwork/ui/src/components/TxModal/TxModal.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/components/TxModal/TxModal'
  >;
}
declare module '@polymathnetwork/ui/src/helpers.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/src/helpers'>;
}
declare module '@polymathnetwork/ui/src/images/svg/briefcase.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/images/svg/briefcase'
  >;
}
declare module '@polymathnetwork/ui/src/images/svg/handshake.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/images/svg/handshake'
  >;
}
declare module '@polymathnetwork/ui/src/images/svg/help.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/src/images/svg/help'>;
}
declare module '@polymathnetwork/ui/src/images/svg/inbox.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/src/images/svg/inbox'>;
}
declare module '@polymathnetwork/ui/src/images/svg/paper-plane.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/images/svg/paper-plane'
  >;
}
declare module '@polymathnetwork/ui/src/images/svg/whitelist.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/images/svg/whitelist'
  >;
}
declare module '@polymathnetwork/ui/src/index.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/src/index'>;
}
declare module '@polymathnetwork/ui/src/offchain.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/src/offchain'>;
}
declare module '@polymathnetwork/ui/src/redux/account/actions.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/redux/account/actions'
  >;
}
declare module '@polymathnetwork/ui/src/redux/account/reducer.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/redux/account/reducer'
  >;
}
declare module '@polymathnetwork/ui/src/redux/common/actions.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/redux/common/actions'
  >;
}
declare module '@polymathnetwork/ui/src/redux/common/reducer.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/ui/src/redux/common/reducer'
  >;
}
declare module '@polymathnetwork/ui/src/redux/helpers.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/src/redux/helpers'>;
}
declare module '@polymathnetwork/ui/src/redux/reducer.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/src/redux/reducer'>;
}
declare module '@polymathnetwork/ui/src/specsInit.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/src/specsInit'>;
}
declare module '@polymathnetwork/ui/src/validate.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/src/validate'>;
}
declare module '@polymathnetwork/ui/webpack.dev.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/webpack.dev'>;
}
declare module '@polymathnetwork/ui/webpack.prod.js' {
  declare module.exports: $Exports<'@polymathnetwork/ui/webpack.prod'>;
}
