version: 2.1

references:
  container_config: &container_config
    docker:
      - image: 'circleci/node:8-stretch'
  restore_yarn_cache: &restore_yarn_cache
    restore_cache:
      name: Restore Yarn Package Cache
      keys:
        - yarn-packages-{{ checksum "yarn.lock" }}
  save_cache: &save_cache
    save_cache:
      name: Save Yarn Package Cache
      key: yarn-packages-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn
  yarn_install: &yarn_install
    run:
      name: Yarn install
      command: yarn install --frozen-lockfile

jobs:
  new_issuer_test:
    <<: *container_config
    steps:
      - checkout
      - *restore_yarn_cache
      - *yarn_install
      - *save_cache
      - run: yarn test:new-issuer
  new_issuer_build:
    <<: *container_config
    steps:
      - checkout
      - *restore_yarn_cache
      - *yarn_install
      - *save_cache
      - run: yarn build:new-issuer
  issuer_build:
    <<: *container_config
    steps:
      - checkout
      - *restore_yarn_cache
      - *yarn_install
      - *save_cache
      - run: yarn build:issuer
  issuer_test:
    <<: *container_config
    steps:
      - checkout
      - *restore_yarn_cache
      - *yarn_install
      - *save_cache
      - run: yarn test:issuer
  ui_test:
    <<: *container_config
    steps:
      - checkout
      - *restore_yarn_cache
      - *yarn_install
      - *save_cache
      - run: yarn test:ui
  new_sdk_test:
    <<: *container_config
    steps:
      - checkout
      - *restore_yarn_cache
      - *yarn_install
      - *save_cache
      - run: yarn test:sdk
  new_ui_test:
    <<: *container_config
    steps:
      - checkout
      - *restore_yarn_cache
      - *yarn_install
      - *save_cache
      - run: yarn test:new-ui
  new_shared_test:
    <<: *container_config
    steps:
      - checkout
      - *restore_yarn_cache
      - *yarn_install
      - *save_cache
      - run: yarn test:new-shared

workflows:
  version: 2
  new_issuer_jobs:
    jobs:
      - new_issuer_test
  new_ui_jobs:
    jobs:
      - new_ui_test
  new_sdk_jobs:
    jobs:
      - new_sdk_test
  new_shared_jobs:
    jobs:
      - new_shared_test
  issuer_jobs:
    jobs:
      - issuer_test
  ui_jobs:
    jobs:
      - ui_test
  offchain_jobs:
    jobs:
      - offchain_test
