version: 2.1

references:
  container_config: &container_config
    docker:
      - image: 'circleci/node:lts'
  restore_yarn_cache: &restore_yarn_cache
    restore_cache:
      name: Restore Yarn Package Cache
      keys:
        - yarn-packages-{{ checksum "yarn.lock" }}
  save_cache: &save_cache
    save_cache:
      name: Save Yarn Package Cache
      key: yarn-packages-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn
  yarn_install: &yarn_install
    run:
      name: Yarn install
      command: yarn install --frozen-lockfile

jobs:
  test:
    <<: *container_config
    steps:
      - checkout
      - *restore_yarn_cache
      - *yarn_install
      - *save_cache
      - run: yarn test
  build:
    <<: *container_config
    steps:
      - checkout
      - *restore_yarn_cache
      - *yarn_install
      - *save_cache
      - run: yarn build

workflows:
  version: 2
  test_packages:
    jobs:
      - test:
          filters:
            branches:
              only: feature/implement-circle-ci-deployments
      - build:
          filters:
            branches:
              only: feature/implement-circle-ci-deployments
