export const POLYMATH_REGISTRY_ADDRESS_LOCAL = process.env
  .POLYMATH_REGISTRY_ADDRESS_LOCAL as string;
export const POLYMATH_REGISTRY_ADDRESS_KOVAN = process.env
  .POLYMATH_REGISTRY_ADDRESS_KOVAN as string;
