// flow-typed signature: 1b60d8488df603980ab0f1307a4a306d
// flow-typed version: <<STUB>>/@polymathnetwork/shared_v0.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@polymathnetwork/shared'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@polymathnetwork/shared' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@polymathnetwork/shared/flow-typed/npm/@babel/core_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/shared/flow-typed/npm/@babel/node_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/shared/flow-typed/npm/@babel/plugin-proposal-class-properties_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/shared/flow-typed/npm/@babel/plugin-transform-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/shared/flow-typed/npm/@babel/preset-env_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/shared/flow-typed/npm/@babel/preset-flow_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/shared/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/shared/flow-typed/npm/ganache-cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/shared/flow-typed/npm/jest_v22.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/shared/flow-typed/npm/polymath-core_vx.x.x' {
  declare module.exports: any;
}

declare module '@polymathnetwork/shared/flow-typed/npm/truffle_vx.x.x' {
  declare module.exports: any;
}

// Filename aliases
declare module '@polymathnetwork/shared/flow-typed/npm/@babel/core_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/shared/flow-typed/npm/@babel/core_vx.x.x'
  >;
}
declare module '@polymathnetwork/shared/flow-typed/npm/@babel/node_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/shared/flow-typed/npm/@babel/node_vx.x.x'
  >;
}
declare module '@polymathnetwork/shared/flow-typed/npm/@babel/plugin-proposal-class-properties_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/shared/flow-typed/npm/@babel/plugin-proposal-class-properties_vx.x.x'
  >;
}
declare module '@polymathnetwork/shared/flow-typed/npm/@babel/plugin-transform-runtime_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/shared/flow-typed/npm/@babel/plugin-transform-runtime_vx.x.x'
  >;
}
declare module '@polymathnetwork/shared/flow-typed/npm/@babel/preset-env_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/shared/flow-typed/npm/@babel/preset-env_vx.x.x'
  >;
}
declare module '@polymathnetwork/shared/flow-typed/npm/@babel/preset-flow_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/shared/flow-typed/npm/@babel/preset-flow_vx.x.x'
  >;
}
declare module '@polymathnetwork/shared/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/shared/flow-typed/npm/flow-bin_v0.x.x'
  >;
}
declare module '@polymathnetwork/shared/flow-typed/npm/ganache-cli_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/shared/flow-typed/npm/ganache-cli_vx.x.x'
  >;
}
declare module '@polymathnetwork/shared/flow-typed/npm/jest_v22.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/shared/flow-typed/npm/jest_v22.x.x'
  >;
}
declare module '@polymathnetwork/shared/flow-typed/npm/polymath-core_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/shared/flow-typed/npm/polymath-core_vx.x.x'
  >;
}
declare module '@polymathnetwork/shared/flow-typed/npm/truffle_vx.x.x.js' {
  declare module.exports: $Exports<
    '@polymathnetwork/shared/flow-typed/npm/truffle_vx.x.x'
  >;
}
